kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: fleet-test
  namespace: fleet-default
spec:
  branch: test
  repo: https://github.com/fmt91/fleet
  paths:
  - multi/helm
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test
